### ISSUE TITLE
Using enhancement proposals

### ISSUE THREAD

**Issue by misterdjules** [jasnell/dev-policy#36]
It seems that one of the main differences between Node.js and io.js is the approach they take when considering changes. Node.js seems to be more conservative and io.js seems to be more driven by innovation.

My understanding is that the concept of LTS branches/releases and development/bleeding edge branches/releases have been used in the current document to represent this difference.

However, I'm concerned that without proper communication between the LTS working group and the rest of the core team at the early stage of the design of new innovative features, there would be too much tension between these two groups to allow them to work together.

For instance, let's imagine that a new feature that is implemented in a similar way than the `cluster` module lands in a non-LTS release without any communication with the LTS working group. Because such a feature would be intertwined in so many other subsystems, it would be very difficult for the LTS working group to not include this feature in the next LTS release, even if it doesn't meet their standards.

I don't have any experience with using formal "enhancement proposals" in any project, but I've read some of the ones that have been submitted in libuv/libuv and followed the conservations around them. It seems to work well for them.

I think that having Node Enhancement Proposals would help catch divergence of opinions early, and allow for some iterations at the design stage of new features such that both LTS working group members and other collaborators of the project could make sure that new features are in line with the goals of the LTS working group.

Thoughts?

**Comment by jasnell** [comment]
This is similar to mechanisms that are used in other open foundation type projects like OpenStack and Docker. Those models are worth paying attention to and could inform the discussion here quite a bit.

**Comment by misterdjules** [comment]
For more information, here is the repository where libuv keeps track of their enhancement proposals: https://github.com/libuv/leps/.

**Comment by mikeal** [comment]
> io.js seems to be more driven by innovation

I wouldn't quite phrase it like this. There's a false perception here that io.js is quickly landing considerable changes without ample time for the effects of that change to be considered by people who are watching but haven't been given enough time to respond. That just isn't true.

When sizable changes are proposed in PRs they get reviewed very thoroughly, sometimes over a period longer than a month, and that is plenty of time for the LTS WG and others to weigh in. My biggest concern with a formal proposal system is that it will be used to hold up working code landing in the tree. It's actually a _lot_ easier to understand the scope of a change by reading a PR for it than reading an abstract proposal. Furthermore this formalized process for writing the abstract is a barrier to entry for many developers who would likely have written the feature if not for having to jump through all these hoops. 

However, there are features I could imagine that require a good deal of extra coordination to author where it would be hard to do that coordination with _only_ a PR as it sort of puts the burden of implementation on a single person. For features of that size and scope we should just form a temporary WG around them and make sure that people from other related WGs, like LTS, have a chance to get in.

**Comment by misterdjules** [comment]
> I wouldn't quite phrase it like this. There's a false perception here that io.js is quickly landing
> considerable changes without ample time for the effects of that change to be considered by people
> who are watching but haven't been given enough time to respond. That just isn't true.

It is also not what I wrote. Being driven by innovation is not mutually exclusive with carefully landing changes.

> When sizable changes are proposed in PRs they get reviewed very thoroughly, sometimes over a
> period longer than a month, and that is plenty of time for the LTS WG and others to weigh in. 

And if these PRs require significant changes, their authors and reviewers will have to spend a lot of time addressing concerns that could have been expressed earlier.

> My biggest concern with a formal proposal system is that it will be used to hold up working code
> landing in the tree.

There is no reason why a good design document would prevent any code from landing in the tree. Similarly, the current PRs review process could prevent some badly designed feature to land in the tree, I don't see that as a problem, it's actually what I expect from a review process.

The difference here is that the code review process happens much later in the development process, and rejecting or requiring major changes when a lot of work went through the implementation is more frustrating for everyone than doing that at the design stage.

These enhancements proposals would not be used for most changes. It would be used only for changes that would be large enough that it would help both the author of the changes and the reviewers to integrate the change.

> It's actually a lot easier to understand the scope of a change by reading a PR for it than reading an
> abstract proposal.

It is easier to understand the scope of a change by reading a PR. It also takes a lot more time to implement a feature than to come up with the initial design. Having feedback early with a design document is not mutually exclusive with reviewing a PR later. The design review helps everyone to have a better PR to review down the line.

For instance, would an "enhancement proposal" document have helped the [workers implementation PR in io.js](https://github.com/iojs/io.js/pull/1159)?

> Furthermore this formalized process for writing the abstract is a barrier to entry for many developers
> who would likely have written the feature if not for having to jump through all these hoops.

The process as used by the libuv project for instance is to submit a PR with a text file that follows some very loose conventions. It doesn't seem to me to be an higher barrier to entry than, for instance, implementing something equivalent to the `cluster` module from scratch.

> However, there are features I could imagine that require a good deal of extra coordination to author
> where it would be hard to do that coordination with only a PR as it sort of puts the burden of
> implementation on a single person. For features of that size and scope we should just form a
> temporary WG around them and make sure that people from other related WGs, like LTS, have a
> chance to get in.

That sounds more or less like what I described originally, except that it would require creating a new working group instead of writing a short design document. That seems like an higher barrier to entry.

I don't have anything against creating working groups though if their goal is, in these cases, to have one design document as part of their deliverables at the first stage of the process.

**Comment by mikeal** [comment]
> It is also not what I wrote.

You're right, my apologies.

**Comment by mikeal** [comment]
There are two assumptions here which I think are not always true:
1. That people who could write a patch for a feature could more easily write a proposal.
2. That proposals are easier to review than a patch.

Worker Threads, which you bring up, are actually a perfect example https://github.com/iojs/io.js/pull/1159

Worker threads would certainly be a proposal if we had a proposal system in place. Instead we have an in-progress PR with 25 days of reviews and discussion as the API and implementation are flushed out. The PR was sent before it was ready to merge in order to get iterative feedback as the implementation progressed and it is still, even by the authors own opinion, not ready to merge.

To me this is a much better process than trying to dream up the perfect API and design and then to have a bunch of people meditate on the impact the potential implementation it would have. In fact, I think that something like this, which is getting a lot of positive traction as a PR, would be decimated by negative concerns over its impact were it a proposal. If you look towards the end at Rod's comment you can see those kinds of concerns still but those aren't the focus of the review (which is mostly positive). Open discussions about ideas can be a lightning rod for negativity from the community because the barrier to participation is so low as the focus of participation focus is _ideas_ and _opinions about ideas_. Having real code raises the bar quite a bit and tends to keep things on a more positive track.

**But** I can see an argument for features that are just far too much work to propose as a PR where people won't bother unless they know it has some chance of getting in. How about this.
- No feature _requires_ an enhancement proposal.
- We define a format for enhancement proposals people can use where appropriate.

This way we can iterate on a proposal format that works well and is accessible to people that need it but we avoid the possibility of changes getting kicked back and told to write a proposal instead. We should also make it clear that working code wins. Someone might write a great proposal but if nothing actually works we shouldn't hold up progress on working code changes to wait for it. We have to make sure we avoid putting the project in a state of stagnation by waiting on well defined ideas that don't actually exist yet.

**Comment by jasnell** [comment]
There's really nothing wrong with a "The Code is the Proposal" kind of approach for these things, and an openly iterative process is certainly superior. This really is the kind of thing the notion of Development Branches is for -- allowing complex ideas and changes to evolve, reaching a point of maturity before they flow into the master. Perhaps we don't need a strict policy on this so much as a reasonably straight forward best practice of: if you're looking at and working on a reasonably complex problem or change, seek input as early and as often as possible, document what you're trying to achieve, work in the open, and accept input and feedback throughout the process. When you think you've got something that looks solid, bring it to folks attention early enough that they have time to review it and kick the tires. Dropping significant new functionality less than 48 hours before an `-rc.1` cut likely isn't going to go over too well.

**Comment by mhdawson** [comment]
In terms of:

For instance, let's imagine that a new feature that is implemented in a similar way than the cluster module lands in a non-LTS release without any communication with the LTS working group. Because such a feature would be intertwined in so many other subsystems, it would be very difficult for the LTS working group to not include this feature in the next LTS release, even if it doesn't meet their standards

I think the model has to be the next LTS includes everything in master at the time it's cut.  I believe that trying to remove features or only including a subset of changes will be too difficult.   We'd probably have to cut the LTS and if there are issues,  work in the new branch to resolve them.  It would be important to co-ordinate in order to minimize getting large changes by surprise just before an LTS branch.  In the case where it occurs then we'd probably have to branch the LTS from an earlier level.

**Comment by jasnell** [comment]
In cases like that, it needs to be expected that the LTS WG is closely watching what's happening in the master... actually, scratch that, ideally the members of the LTS WG are _helping_ to drive what's happening in the master. The LTS WG cannot be operating in isolation from the rest of the project.

**Comment by mhdawson** [comment]
I agree but when you say "helping" to drive what's happening in the master I think it would be through communication in respect to the LTS plans and providing ways for people to let them know in advance if something bigger is coming as opposed to any sort of checks/balances.  Of course I also hope we'll have people  both driving their own content into master as well as contributing to the LTS efforts.

**Comment by misterdjules** [comment]
@mikeal 

> There are two assumptions here which I think are not always true:
> 
> That people who could write a patch for a feature could more easily write a proposal.
> That proposals are easier to review than a patch.

That proposal can be a PR with code, it doesn't have to be prose. I was not suggesting a specific format, but more a way for external contributors to gather initial feedback and for project's members to get an early heads up about potentially major changes.

> Worker Threads, which you bring up, are actually a perfect example iojs/io.js#1159
> 
> Worker threads would certainly be a proposal if we had a proposal system in place. Instead we have > an in-progress PR with 25 days of reviews and discussion as the API and implementation are
> flushed out. The PR was sent before it was ready to merge in order to get iterative feedback as the 
> implementation progressed and it is still, even by the authors own opinion, not ready to merge.

I didn't realize that the workers implementation's PR was submitted before it was ready to merge. So it seems to me that it's indeed a great example of something like an enhancement proposal. How can we encourage that type of PRs in the merged project?

> To me this is a much better process than trying to dream up the perfect API and design and then to
> have a bunch of people meditate on the impact the potential implementation it would have.

I don't think I suggested to "dream up" anything or to have group meditation sessions, although that's an interesting idea :)

> In fact, I think that something like this, which is getting a lot of positive traction as a PR, would be
> decimated by negative concerns over its impact were it a proposal. If you look towards the end at
> Rod's comment you can see those kinds of concerns still but those aren't the focus of the review 
> (which is > mostly positive). Open discussions about ideas can be a lightning rod for negativity from > the  community because the barrier to participation is so low as the focus of participation focus is 
> ideas  and opinions about ideas. Having real code raises the bar quite a bit and tends to keep things > on a more positive track.

I agree that having code would make enhancement proposals better. I think having a design document like [the original comment in the Workers implementation PR](https://github.com/iojs/io.js/pull/1159#issue-61913462) helps too though.

> How about this.
> 
> No feature requires an enhancement proposal.
> We define a format for enhancement proposals people can use where appropriate.
> This way we can iterate on a proposal format that works well and is accessible to people that need it > but we avoid the possibility of changes getting kicked back and told to write a proposal instead. 

Without making them mandatory, how can we encourage people to use these enhancement proposals? Maybe we can mention them in the dev policy or in a "contributing" document?

> We should also make it clear that working code wins. Someone might write a great proposal but if 
> nothing actually works we shouldn't hold up progress on working code changes to wait for it. We 
> have to make sure we avoid putting the project in a state of stagnation by waiting on well defined 
> ideas that don't actually exist yet.

That seems obvious.

**Comment by jasnell** [comment]
Having a `work-in-progress` tag for PR's and encouraging it's use via the Contributing document and even a quick note in the dev-policy should work. A PR with the `work-in-progress` tag would be a clear indication that it's not yet ready to land. From there it's a matter of encouraging best practices and ensuring that the core contributors are leading by example whenever they are working on significant new features.

**Comment by Fishrock123** [comment]
> Maybe we can mention them in the dev policy or in a "contributing" document?

In the contributing document/readme + on the website might be workable.
