### ISSUE TITLE
Getting feedback from Node.js/io.js users

### ISSUE THREAD

**Issue by misterdjules** [jasnell/dev-policy#39]
It seems clear that both the Node.js and io.js projects have their users' best interests in mind. However, we haven't yet involved any user outside of both projects' collaborators in the process for writing this development policy.

I think it is important to get the feedback from a variety of users on some of the issues discussed in this document, notably anything related to releases (LTS, frequency, content, process) and the stability policy.

How can we involve these users such that the largest spectrum of users is represented?

**Comment by mikeal** [comment]
@misterdjules in io.js we did a big outreach effort when we built the roadmap. We got a lot of input from end user developers as well as surveying a bunch of companies. That feedback lead to the first real mention and consideration of an LTS WG strategy in io.js. It also lead to the Stability Policy. That feedback also re-enforced that there is a large demand for new releases and forward progress within those new releases.

That feedback directly influenced io.js' policies which in many areas are the basis for policies here. If we want to continue to gather feedback from the community and iterate on these policies I think that we should do so by continuing the Roadmap WG and finding even better ways of collecting feedback from the community.

**Comment by mikeal** [comment]
Also, we should do what we can over the next few days to promote this repo to the public for their participation.

**Comment by misterdjules** [comment]
@mikeal Do you have the data of that outreach effort somewhere, and information on how the data was collected?

**Comment by mikeal** [comment]
The biggest thread we had was the "pain points" thread: https://github.com/iojs/roadmap/issues/1

Which I eventually distilled in to a wordcloud https://github.com/iojs/roadmap/issues/1#issuecomment-71342191

The corporate feedback we promised to anonymize which I haven't done yet but the feedback came in privately prior to the roadmap work and influenced it quiet a bit.

There are also several other threads, some of which are still active https://github.com/iojs/roadmap/issues

We did a fair amount of outreach on twitter to get people to participate in some of these threads as well.

**Comment by mikeal** [comment]
BTW, this was the _easiest_ way for us to get feedback from a large section of the community. It is somewhat optimized for our own convenience and you'll find threads there about better ways to reach even more of the community through targeted questions or surveys.

This is very much an ongoing process and the more specific we want to get for feedback the more work the WG will have to do in order to collect it.

**Comment by misterdjules** [comment]
@mikeal Do you mean that you have feedback from a significant number of companies listed in https://github.com/iojs/roadmap/issues/13?

https://github.com/iojs/roadmap/issues/1 is definitely very interesting, but it seems that a large number of participants in this thread are collaborators of Node.js/io.js, not users outside of these groups.

**Comment by mikeal** [comment]
Yes, those are the companies we reached out to with standard questions. Most of them responded (but not 100%).

> it seems that a large number of participants in this thread are collaborators of Node.js/io.js, not users outside of these groups.

That thread started before io.js even existed. It began in Node Forward and the reason many of the commenters are _now_ collaborators in io.js is because we started working on the issues they were concerned with.
