### ISSUE TITLE
Which repositories from the two organizations would merge under the foundation?

### ISSUE THREAD

**Issue by jasnell** [jasnell/dev-policy#5]
@mikeal: there's a lot more than just these two repos, there's http-parser in joyent and about 50 repos in iojs. the convergence WG should be figuring out how to best move all of those, not just core.
@jasnell: Agreed but I'm trying not to boil too much ocean right now ;-).
@mikeal: right, but it might be best to just leave this out then, because the way we form the org prior to moving the repos over will need to account for moving everything.
@jasnell: Even if some of the details are left out I think there's still value in calling this out for the discussion on Thursday. I've added an open questions section at the bottom and added this in

**Comment by mikeal** [comment]
All io.js repos should move to the foundation as all of those repos correspond to io.js working groups and core.

Also, I think it's going to be a requirement that we simply rename the io.js org as a starting point for the foundation org because it would be incredibly difficult to rebuild the 50+ teams and almost 300 members as well as the more than 50 repo permissions that get lost if you move a repo to a different org. Keep in mind that io.js core repo is called `io.js` so this doesn't necessarily mean that the io.js core repo is the repo we start with in a reconciled core just because we're starting with the io.js org as a base.

**Comment by mikeal** [comment]
Oh, and `libuv` has its own org https://github.com/libuv/

Even if `libuv` did join the foundation they would probably want to keep that org.

**Comment by Fishrock123** [comment]
`iojs/io.js` and `joyent/node` need to remain linkable points so that existing links from commits still work.

I think moving them preserved redirects, but it's hard to be as sure. :/

**Comment by mikeal** [comment]
@Fishrock123 when i was reading the docs on renaming an org it sounded like it did a lot to resolve this when moving/renaming. we'll only find out how well that works once we do it though.

**Comment by jasnell** [comment]
That's something we can investigate with github.

**Comment by Fishrock123** [comment]
This is underway, so, closing.
